import { useMemo, useState } from "react";
import { CopyOutlined, DownloadOutlined, EditOutlined, MoreOutlined, PictureOutlined, SearchOutlined, SyncOutlined } from "@ant-design/icons";
import { DemoModal, DemoToast } from "./ReplicaCommon";
import "./finance-replica.css";

type Row={id:number;posting:string;product:string;store:string;delivered:string,sales:number,cost:number|null,commission:number,logistics:number,other:number,settlement:number,profit:number,rate:number,sku:string,offer:string};
const INITIAL:Row[]=[
{id:1,posting:"47619823-0007-1",product:"Органайзер для кухни многофункциональный",store:"测试",delivered:"2026-09-23",sales:1399,cost:188,commission:196,logistics:240,other:28,settlement:935,profit:483,rate:34.5,sku:"5743990011",offer:"OZG-240923-001"},
{id:2,posting:"47619510-0012-1",product:"Щетка для удаления шерсти домашних животных",store:"测试",delivered:"2026-09-22",sales:899,cost:96,commission:126,logistics:184,other:18,settlement:571,profit:475,rate:52.8,sku:"5743990012",offer:"OZG-240923-002"},
{id:3,posting:"47619082-0004-1",product:"Держатель телефона автомобильный 360°",store:"UyutHome 家居",delivered:"2026-09-21",sales:1099,cost:null,commission:154,logistics:210,other:22,settlement:713,profit:0,rate:0,sku:"5743990013",offer:"OZG-240923-003"},
{id:4,posting:"47618845-0009-1",product:"Полка для ванной без сверления",store:"测试",delivered:"2026-09-20",sales:1799,cost:240,commission:252,logistics:288,other:36,settlement:1223,profit:983,rate:54.6,sku:"5743990014",offer:"OZG-240923-004"},
];
export function FinanceReplica(){
 const [rows,setRows]=useState(INITIAL);
 const [shop,setShop]=useState("all"); const [keyword,setKeyword]=useState(""); const [financeStatus,setFinanceStatus]=useState(""); const [costStatus,setCostStatus]=useState("");
 const [applied,setApplied]=useState({shop:"all",keyword:"",financeStatus:"",costStatus:""});
 const [rate,setRate]=useState(2); const [syncing,setSyncing]=useState(false); const [toast,setToast]=useState("");
 const [costRow,setCostRow]=useState<Row|null>(null); const [costValue,setCostValue]=useState(0); const [costNote,setCostNote]=useState("");
 const [detail,setDetail]=useState<Row|null>(null); const [moreId,setMoreId]=useState<number|null>(null);
 const flash=(t:string)=>{setToast(t);setTimeout(()=>setToast(""),1500)};
 const visible=useMemo(()=>rows.filter(r=>{if(applied.shop!=="all"&&r.store!==applied.shop)return false;const q=applied.keyword.toLowerCase();if(q&&![r.posting,r.sku,r.offer].some(x=>x.toLowerCase().includes(q)))return false;if(applied.costStatus==="missing"&&r.cost!==null)return false;if(applied.costStatus==="recorded"&&r.cost===null)return false;return true}),[rows,applied]);
 const totals=useMemo(()=>visible.reduce((a,r)=>({sales:a.sales+r.sales,cost:a.cost+(r.cost||0),ozon:a.ozon+r.commission+r.logistics,other:a.other+r.other,profit:a.profit+r.profit}),{sales:0,cost:0,ozon:0,other:0,profit:0}),[visible]);
 const reset=()=>{setShop("all");setKeyword("");setFinanceStatus("");setCostStatus("");setApplied({shop:"all",keyword:"",financeStatus:"",costStatus:""})};
 const saveCost=()=>{if(!costRow)return;setRows(v=>v.map(r=>r.id===costRow.id?{...r,cost:costValue,profit:r.settlement-costValue-r.other,rate:Math.max(0,(r.settlement-costValue-r.other)/r.sales*100)}:r));setCostRow(null);flash("采购成本已保存")};
 const copy=(text:string)=>{navigator.clipboard?.writeText(text);flash("订单号已复制")};
 const sync=()=>{setSyncing(true);setTimeout(()=>{setSyncing(false);flash("财务数据同步完成")},900)};
 const exportFile=()=>{const csv="订单号,商品,销售所得,采购成本,利润\n"+visible.map(r=>[r.posting,r.product,r.sales,r.cost??"",r.profit].join(",")).join("\n");const u=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=u;a.download="ozong-finance-demo.csv";a.click();URL.revokeObjectURL(u);flash("已导出 Excel 兼容 CSV")};
 return <div className="finance-page-source"><DemoToast text={toast}/>
   <section className="finance-summary-source"><div className="finance-head-source"><div><h1>财务中心</h1><p>统计已签收订单的收支情况，支持按结算日期筛选。</p></div><button title="估算利润 = 销售所得 - 采购成本 - Ozon 费用 - 其他支出" onClick={()=>flash("估算利润 = 销售所得 - 采购成本 - Ozon 费用 - 其他支出")}>口径说明</button></div>
    <div className="finance-equation-source">{[["销售所得","₽ "+totals.sales.toFixed(2),"violet"],["采购成本","¥ "+totals.cost.toFixed(2),"amber"],["Ozon 费用","₽ "+totals.ozon.toFixed(2),"blue"],["其他支出","₽ "+totals.other.toFixed(2),"slate"],["估算利润","¥ "+totals.profit.toFixed(2),"green"]].map((m,i)=><span className="eq-item-source" key={m[0]}><article className={m[2]}><small>{m[0]}</small><b>{m[1]}</b>{i===4&&<em>{totals.sales?((totals.profit/totals.sales)*100).toFixed(1):0}%</em>}</article>{i<4&&<strong>−</strong>}</span>)}<article className="pending-source"><small>待财务流水</small><b>3</b><em>不计入利润</em></article></div>
   </section>
   <section className="finance-filter-source"><div className="finance-filter-main-source"><select value={shop} onChange={e=>setShop(e.target.value)}><option value="all">全部店铺</option><option>测试</option><option>UyutHome 家居</option></select><label className="finance-dates-source"><span>签收日期</span><input type="date" defaultValue="2026-06-26"/><i>至</i><input type="date" defaultValue="2026-09-23"/></label><div className="finance-keyword-source"><SearchOutlined/><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="订单号 / SKU / 货号"/></div><select value={financeStatus} onChange={e=>setFinanceStatus(e.target.value)}><option value="">财务状态</option><option value="available">已有财务流水</option><option value="pending">待财务流水</option></select><select value={costStatus} onChange={e=>setCostStatus(e.target.value)}><option value="">成本状态</option><option value="recorded">已录入成本</option><option value="missing">未填</option></select><label className="finance-rate-source"><span>估算规则</span><input type="number" value={rate} onChange={e=>setRate(Number(e.target.value))} onBlur={()=>flash("估算规则已保存")}/><i>%</i></label></div><div className="finance-actions-source"><button className="primary" onClick={()=>setApplied({shop,keyword,financeStatus,costStatus})}>查询</button><button onClick={reset}>重置</button><button onClick={exportFile}><DownloadOutlined/>导出 Excel</button><button className="sync" disabled={syncing} onClick={sync}><SyncOutlined/>{syncing?"同步中…":"同步数据"}</button></div></section>
   <section className="finance-ledger-source"><div className="finance-row-source head"><span>订单 / 商品信息</span><span>销售所得</span><span>采购成本</span><span>销售佣金</span><span>物流费用</span><span>其他支出</span><span>实际所得</span><span>利润 / 利润率</span><span>操作</span></div><div className="finance-scroll-source">{visible.map(r=><div className="finance-row-source" key={r.id}><span className="identity-source"><i><PictureOutlined/></i><span><button onClick={()=>setDetail(r)}>{r.posting}</button><small>{r.product}</small><em>{r.delivered} · {r.store}</em></span><button className="copy" onClick={()=>copy(r.posting)}><CopyOutlined/></button></span><span>₽ {r.sales.toFixed(2)}</span><span><button className="cost-btn-source" onClick={()=>{setCostRow(r);setCostValue(r.cost||0);setCostNote("")}}>{r.cost===null?<em>待补成本</em>:<><b>₽ {r.cost.toFixed(2)}</b><small>采购 ¥ {r.cost.toFixed(2)}</small></>}<EditOutlined/></button></span><span>₽ {r.commission.toFixed(2)}</span><span>₽ {r.logistics.toFixed(2)}</span><span>₽ {r.other.toFixed(2)}</span><span>₽ {r.settlement.toFixed(2)}</span><span className="profit-source">{r.cost===null?<em>等待成本</em>:<><b>₽ {r.profit.toFixed(2)}</b><small>{r.rate.toFixed(1)}%</small></>}</span><span className="finance-row-actions-source"><button onClick={()=>setDetail(r)}>查看明细</button><div className="dropdown-wrap"><button onClick={()=>setMoreId(moreId===r.id?null:r.id)}><MoreOutlined/></button>{moreId===r.id&&<div className="dropdown-menu-source finance-more-source"><button onClick={()=>{setMoreId(null);setCostRow(r);setCostValue(r.cost||0)}}>录入采购成本</button><button onClick={()=>{setMoreId(null);copy(r.posting)}}>复制订单号</button></div>}</div></span></div>)}</div><footer><span>其他支出属于经营支出，不计入 Ozon 费用合计；无财务流水订单不参与金额汇总。</span><div><button className="active">1</button><select><option>30 条/页</option><option>50 条/页</option><option>100 条/页</option></select></div></footer></section>
   <DemoModal open={!!costRow} title="录入本单采购成本" width={480} onClose={()=>setCostRow(null)} onOk={saveCost} okText="保存成本">{costRow&&<><div className="cost-ref-source"><span>订单</span><b>{costRow.posting}</b></div><label className="replica-field"><span>采购成本（人民币）*</span><input type="number" value={costValue} onChange={e=>setCostValue(Number(e.target.value))}/></label><label className="replica-field"><span>备注</span><textarea value={costNote} onChange={e=>setCostNote(e.target.value)} placeholder="例如供应商、采购单号或成本说明（可选）"/></label><p className="finance-note-source">成本保存为订单快照，不会随商品资料的后续变化自动改写。</p></>}</DemoModal>
   {detail&&<div className="finance-drawer-source"><header><b>订单利润详情</b><button onClick={()=>setDetail(null)}>×</button></header><div className="finance-drawer-body-source"><div className="detail-title-source"><span>订单号</span><h2>{detail.posting}<button onClick={()=>copy(detail.posting)}><CopyOutlined/></button></h2><i>已签收</i></div><section><h3>金额概览</h3><div className="amount-grid-source"><span>销售所得<b>₽ {detail.sales}</b></span><span>实际所得<b>₽ {detail.settlement}</b></span><span>采购成本<b>{detail.cost===null?"未填":"¥ "+detail.cost}</b></span><span>其他支出<b>₽ {detail.other} · {rate}%</b></span><span>物流费用<b>₽ {detail.logistics}</b></span><span>估算利润<b className="positive">₽ {detail.profit} · {detail.rate}%</b></span></div></section><section><h3>全部商品</h3><div className="drawer-product-source"><span><b>{detail.product}</b><small>SKU：{detail.sku} · 货号：{detail.offer} · 数量：1</small></span><strong>₽ {detail.sales}</strong></div></section><section><h3>Ozon 财务分录</h3><article className="transaction-source"><header><span><b>销售结算</b><small>{detail.delivered} · OP-{detail.id}8201</small></span><strong>₽ {detail.settlement}</strong></header><div><span>销售所得 ₽ {detail.sales}</span><span>佣金 -₽ {detail.commission}</span><span>物流 -₽ {detail.logistics}</span></div></article></section><section><h3>采购信息</h3><p>{costNote||"尚未填写成本备注。"}</p><button onClick={()=>{setCostRow(detail);setCostValue(detail.cost||0)}}><EditOutlined/> 编辑本单采购成本</button></section></div></div>}
 </div>
}
