import { useMemo, useRef, useState } from "react";
import { CloudUploadOutlined, DeleteOutlined, EditOutlined, EyeOutlined, PictureOutlined, PlusOutlined, ReloadOutlined, SearchOutlined, UploadOutlined } from "@ant-design/icons";
import { DemoModal, DemoToast } from "./ReplicaCommon";
import "./watermark-replica.css";

type Pos="top-left"|"top-center"|"top-right"|"center-left"|"center"|"center-right"|"bottom-left"|"bottom-center"|"bottom-right";
type Wm={id:number;name:string;original:string,size:string,preview:string;position:Pos;width:number;opacity:number;created:string};
const INITIAL:Wm[]=[
{id:1,name:"星桥家居品牌标识",original:"xingqiao-logo.png",size:"52.6 KB",preview:"星桥",position:"bottom-right",width:18,opacity:74,created:"2026-09-21 10:18:26"},
{id:2,name:"远航百货店铺角标",original:"yuanhang-badge.webp",size:"38.1 KB",preview:"远航",position:"top-left",width:15,opacity:86,created:"2026-09-22 15:06:44"},
{id:3,name:"秋季活动促销水印",original:"autumn-sale.png",size:"67.9 KB",preview:"SALE",position:"top-right",width:21,opacity:68,created:"2026-09-23 09:32:18"},
];
const POS:{value:Pos,label:string,short:string}[]=[
{value:"top-left",label:"左上角",short:"左上"},{value:"top-center",label:"顶部居中",short:"上中"},{value:"top-right",label:"右上角",short:"右上"},
{value:"center-left",label:"左侧居中",short:"左中"},{value:"center",label:"中心",short:"中心"},{value:"center-right",label:"右侧居中",short:"右中"},
{value:"bottom-left",label:"左下角",short:"左下"},{value:"bottom-center",label:"底部居中",short:"下中"},{value:"bottom-right",label:"右下角",short:"右下"},
];
const labelPos=(p:Pos)=>POS.find(x=>x.value===p)?.label||"右下角";
export function WatermarkReplica(){
 const [rows,setRows]=useState(INITIAL); const [keyword,setKeyword]=useState(""); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [applied,setApplied]=useState({keyword:"",from:"",to:""});
 const [selected,setSelected]=useState<number[]>([]); const [editor,setEditor]=useState<Wm|null|undefined>(undefined); const [preview,setPreview]=useState<Wm|null>(null); const [deleteTarget,setDeleteTarget]=useState<Wm|null>(null); const [batchDelete,setBatchDelete]=useState(false);
 const [form,setForm]=useState({name:"",width:20,opacity:100,position:"bottom-right" as Pos,preview:""}); const [toast,setToast]=useState(""); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(10); const inputRef=useRef<HTMLInputElement|null>(null);
 const flash=(t:string)=>{setToast(t);setTimeout(()=>setToast(""),1500)};
 const filtered=useMemo(()=>rows.filter(r=>{const q=applied.keyword.toLowerCase();if(q&&!r.name.toLowerCase().includes(q))return false;if(applied.from&&r.created.slice(0,10)<applied.from)return false;if(applied.to&&r.created.slice(0,10)>applied.to)return false;return true}),[rows,applied]);
 const all=filtered.length>0&&filtered.every(r=>selected.includes(r.id));
 const openCreate=()=>{setEditor(null);setForm({name:"",width:20,opacity:100,position:"bottom-right",preview:""});};
 const openEdit=(r:Wm)=>{setEditor(r);setForm({name:r.name,width:r.width,opacity:r.opacity,position:r.position,preview:r.preview})};
 const chooseFile=()=>inputRef.current?.click();
 const file=(f?:File)=>{if(!f)return;if(f.size>5*1024*1024){flash("水印图片不能超过 5MB");return}if(!["image/png","image/jpeg","image/webp"].includes(f.type)){flash("仅支持 PNG、JPG、WebP 图片");return}const reader=new FileReader();reader.onload=()=>setForm(v=>({...v,preview:String(reader.result||"")}));reader.readAsDataURL(f)};
 const save=()=>{if(!form.name.trim()){flash("请输入模板名称");return}if(editor===null&&!form.preview){flash("请上传水印图片");return}if(editor){setRows(v=>v.map(r=>r.id===editor.id?{...r,name:form.name,width:form.width,opacity:form.opacity,position:form.position,preview:form.preview||r.preview}:r));flash("水印模板已更新")}else{setRows(v=>[{id:Date.now(),name:form.name,original:"watermark.png",size:"42.0 KB",preview:form.preview||"OzonG",position:form.position,width:form.width,opacity:form.opacity,created:"2026-09-24 10:00:00"},...v]);flash("水印模板已创建")}setEditor(undefined)};
 const removeOne=()=>{if(deleteTarget){setRows(v=>v.filter(r=>r.id!==deleteTarget.id));setSelected(v=>v.filter(id=>id!==deleteTarget.id));setDeleteTarget(null);flash("水印模板已删除")}};
 const removeBatch=()=>{setRows(v=>v.filter(r=>!selected.includes(r.id)));const n=selected.length;setSelected([]);setBatchDelete(false);flash("已删除 "+n+" 个水印模板")};
 const reset=()=>{setKeyword("");setFrom("");setTo("");setApplied({keyword:"",from:"",to:""});setPage(1);setSelected([])};
 const posStyle=(p:Pos,width:number,opacity:number)=>{const [v,h]=p==="center"?["center","center"]:p.split("-");const st:any={width:width+"%",opacity:opacity/100};if(v==="top")st.top="4%";else if(v==="bottom")st.bottom="4%";else{st.top="50%";st.transform="translateY(-50%)"}if(h==="left")st.left="4%";else if(h==="right")st.right="4%";else{st.left="50%";st.transform=v==="center"?"translate(-50%,-50%)":"translateX(-50%)"}return st};
 return <div className="watermark-page-source"><DemoToast text={toast}/><section className="watermark-card-source">
   <header className="wm-page-head-source"><div><div><h1>水印管理</h1><i>图片水印</i></div><p>集中管理当前账号的品牌水印，为后续商品图片处理做好模板准备。</p></div><button className="primary" onClick={openCreate}><PlusOutlined/> 新增水印</button></header>
   <div className="wm-filter-source"><div><label className="wm-search-source"><SearchOutlined/><input value={keyword} onChange={e=>setKeyword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setApplied({keyword,from,to})} placeholder="搜索模板名称"/></label><label className="wm-dates-source"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>至</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="primary" onClick={()=>{if(from&&to&&from>to){flash("开始日期不能晚于结束日期");return}setApplied({keyword,from,to});setPage(1);setSelected([])}}><SearchOutlined/> 查询</button><button onClick={reset}>重置</button></div><div>{selected.length>0&&<span>已选 {selected.length} 项</span>}<button className="danger" disabled={!selected.length} onClick={()=>setBatchDelete(true)}><DeleteOutlined/> 批量删除</button><button onClick={()=>flash("水印列表已刷新")}><ReloadOutlined/></button></div></div>
   <div className="wm-table-shell-source"><div className="wm-row-source head"><span><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:filtered.map(r=>r.id))}/></span><span>序号</span><span>模板名称</span><span>水印类型</span><span>水印内容</span><span>水印位置</span><span>参数</span><span>创建时间</span><span>操作</span></div><div className="wm-scroll-source">{filtered.map((r,i)=><div className={"wm-row-source "+(selected.includes(r.id)?"selected":"")} key={r.id}><span><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>setSelected(v=>v.includes(r.id)?v.filter(x=>x!==r.id):[...v,r.id])}/></span><span>{(page-1)*pageSize+i+1}</span><span className="wm-name-source"><b>{r.name}</b><small>{r.original} · {r.size}</small></span><span><i className="kind-source">图片水印</i></span><span><button className="wm-thumb-source" onClick={()=>setPreview(r)}>{r.preview.startsWith("data:")?<img src={r.preview}/>:<b>{r.preview}</b>}</button></span><span><i className="pos-pill-source">{labelPos(r.position)}</i></span><span className="wm-settings-source">宽度 {r.width}%<small>不透明度 {r.opacity}%</small></span><span>{r.created}</span><span className="wm-ops-source"><button onClick={()=>setPreview(r)}><EyeOutlined/>查看</button><button onClick={()=>openEdit(r)}><EditOutlined/>编辑</button><button className="danger" onClick={()=>setDeleteTarget(r)}><DeleteOutlined/>删除</button></span></div>)}</div><footer><span>共 {filtered.length} 条记录</span><div><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option value={10}>10 条/页</option><option value={20}>20 条/页</option><option value={50}>50 条/页</option></select><button disabled={page<=1} onClick={()=>setPage(page-1)}>‹</button><button className="active" onClick={()=>setPage(1)}>1</button><button disabled={page>=1} onClick={()=>setPage(page+1)}>›</button></div></footer></div>
  </section>
  {editor!==undefined&&<div className="wm-editor-mask-source"><div className="wm-editor-source"><header><b>{editor?"编辑水印模板":"创建水印模板"}</b><button onClick={()=>setEditor(undefined)}>×</button></header><div className="wm-editor-layout-source"><section><label className="replica-field"><span>* 模板名称</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} maxLength={100} placeholder="请输入便于识别的模板名称"/></label><label className="replica-field"><span>水印类型</span><input disabled value="图片水印"/></label><div className="wm-upload-field-source"><span>{editor?"水印图片":"* 水印图片"}</span><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>file(e.target.files?.[0])}/><button className="wm-upload-zone-source" onClick={chooseFile} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();file(e.dataTransfer.files?.[0])}}>{form.preview?<span className="upload-preview-source">{form.preview.startsWith("data:")?<img src={form.preview}/>:<b>{form.preview}</b>}</span>:<CloudUploadOutlined/>}<span><b>{form.preview?"点击替换当前图片":"点击或拖拽上传图片"}</b><small>支持 PNG、JPG、WebP，最大 5MB、4096×4096</small></span><em><UploadOutlined/>选择图片</em></button><p><PictureOutlined/> 推荐使用透明背景 PNG 或 WebP，显示效果更自然。</p></div><label className="wm-slider-source"><span>水印宽度 <b>{form.width}%</b></span><input type="range" min="5" max="60" value={form.width} onChange={e=>setForm({...form,width:Number(e.target.value)})}/><small>占目标商品图片宽度的比例</small></label><label className="wm-slider-source"><span>不透明度 <b>{form.opacity}%</b></span><input type="range" min="5" max="100" value={form.opacity} onChange={e=>setForm({...form,opacity:Number(e.target.value)})}/></label><div className="wm-position-source"><span>水印位置</span><div><div>{POS.map(p=><button className={form.position===p.value?"selected":""} onClick={()=>setForm({...form,position:p.value})} key={p.value}>{p.short}</button>)}</div><b>{labelPos(form.position)}</b></div></div></section><aside><header><span><b>预览效果</b><small>3:4 商品图片画布</small></span><em>{form.width}% · {form.opacity}%</em></header><div className="wm-canvas-source"><div className="mock-product-source">商品图</div>{form.preview&&<div className="wm-overlay-source" style={posStyle(form.position,form.width,form.opacity)}>{form.preview.startsWith("data:")?<img src={form.preview}/>:<b>{form.preview}</b>}</div>}</div><p>实际应用时会按原图尺寸等比例缩放水印，不拉伸图片。</p></aside></div><footer><button onClick={()=>setEditor(undefined)}>取消</button><button className="primary" onClick={save}>{editor?"保存修改":"创建模板"}</button></footer></div></div>}
  <DemoModal open={!!preview} title="水印效果预览" width={520} onClose={()=>setPreview(null)}>{preview&&<div className="wm-detail-preview-source"><div><b>{preview.name}</b><span>{labelPos(preview.position)} · 宽度 {preview.width}% · 不透明度 {preview.opacity}%</span></div><div className="wm-canvas-source large"><div className="mock-product-source">商品图</div><div className="wm-overlay-source" style={posStyle(preview.position,preview.width,preview.opacity)}>{preview.preview.startsWith("data:")?<img src={preview.preview}/>:<b>{preview.preview}</b>}</div></div></div>}</DemoModal>
  <DemoModal open={!!deleteTarget} title="删除水印模板？" onClose={()=>setDeleteTarget(null)} onOk={removeOne} okText="删除" danger><p>“{deleteTarget?.name}”及其 COS 图片将被永久删除。</p></DemoModal>
  <DemoModal open={batchDelete} title={"删除选中的 "+selected.length+" 个水印模板？"} onClose={()=>setBatchDelete(false)} onOk={removeBatch} okText="批量删除" danger><p>对应的 COS 图片也会一并删除，此操作不可撤销。</p></DemoModal>
 </div>
}
